# Generated by Django 5.1 on 2024-08-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('savings', 'Savings Account'), ('checking', 'Checking Account'), ('credit', 'Credit Card'), ('debit', 'Debit Card'), ('mobile', 'Mobile Wallet'), ('cash', 'Cash')], max_length=10),
        ),
    ]
