# Generated by Django 5.1 on 2024-08-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_bankaccount_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseincome',
            name='type',
            field=models.CharField(choices=[('Expense', 'Expense'), ('Income', 'Income')], max_length=255),
        ),
    ]
