# Generated by Django 5.1 on 2024-08-16 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_card_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseincome',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.card'),
        ),
    ]
