# Generated by Django 5.1 on 2024-08-18 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_expenseincome_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.card')),
            ],
        ),
    ]
