# Generated by Django 5.1 on 2024-09-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_creditcard_loanaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='available_credit',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='credit_used',
        ),
    ]
