# Generated by Django 5.1 on 2024-08-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_card_credit_limit_card_interest_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='available_credit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='credit_used',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
