# Generated by Django 5.1 on 2024-09-04 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_creditcard_available_credit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='credit_limit',
        ),
    ]
