# Generated by Django 5.1 on 2024-08-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_balance_last_balance_balance_last_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='last_payment_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
