# Generated by Django 5.1 on 2024-09-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_creditcard_credit_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='interest',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
