# Generated by Django 5.1 on 2024-09-05 10:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_creditcard_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanaccount',
            name='last_interest_update',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='last_payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='principal_remaining',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
