# Generated by Django 5.1 on 2024-08-19 16:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_balance_last_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='interest',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='balance',
            name='last_payment_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
