# Generated by Django 5.1 on 2024-08-19 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_balance_interest_alter_balance_last_payment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='last_balance',
            new_name='last_interest_paid',
        ),
    ]
