# Generated by Django 5.1 on 2024-09-05 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_loanaccount_last_interest_update_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanaccount',
            old_name='principal_remaining',
            new_name='loan_remaining',
        ),
    ]
