# Generated by Django 5.1 on 2024-09-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_loanaccount_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='transfer_rate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
